name = "NetCDFTools"
uuid = "13b2da74-5743-4fb0-a7fd-ee492c7bd322"
authors = ["Dongdong Kong <kongdd@users.noreply.github.com>"]
version = "0.2.1"

[deps]
CFTime = "179af706-886a-5703-950a-314cd64e0468"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Ipaper = "e58298cb-69f7-4186-aecd-5834b6793426"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[weakdeps]
RCall = "6f49c342-dc21-5d91-9882-a32aef131414"

[extensions]
RbaseTerraExt = "RCall"

[compat]
CFTime = "0.1"
DataFrames = "1.6"
DocStringExtensions = "0.9"
Ipaper = "0.2"
NCDatasets = "0.13, 0.14"
Parameters = "0.12"
PrecompileTools = "1.2"
ProgressMeter = "1"
Reexport = "1.2"
StatsBase = "0.34, 0.35"
julia = "1.9"

[extras]
RCall = "6f49c342-dc21-5d91-9882-a32aef131414"
